"""initial schema

Revision ID: c6b6e2c7ed6b
Revises: 
Create Date: 2026-04-14 01:51:55.950817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b6e2c7ed6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'seller', 'admin', name='user_roles'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=True),
    sa.Column('seller_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('seller_code')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('target_ref', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('voucher_code', sa.String(length=50), nullable=True),
    sa.Column('loyalty_redeemed', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('earn', 'redeem', 'expire', 'adjust', name='loyalty_type'), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_ref', sa.String(length=30), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('installment_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_ref')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_ref', sa.String(length=30), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('discount_type', sa.Enum('percent', 'fixed', name='voucher_type'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('combinable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('voucher_ref')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_ref', sa.String(length=30), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'packed', 'shipped', 'delivered', 'past_due', 'refunded', 'cancelled', name='order_status'), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('loyalty_redeemed', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('full_pay', 'installment', name='payment_method'), nullable=True),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_ref')
    )
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('downpayment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_interest', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'defaulted', name='installment_status'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rrt_ref', sa.String(length=30), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_urls', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'refund_requested', 'refunded', name='rrt_status'), nullable=True),
    sa.Column('seller_notes', sa.Text(), nullable=True),
    sa.Column('restocked_qty', sa.Integer(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('paymongo_refund_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rrt_ref')
    )
    op.create_table('installment_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'past_due', name='schedule_status'), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installment_schedule')
    op.drop_table('return_requests')
    op.drop_table('order_items')
    op.drop_table('installment_plans')
    op.drop_table('orders')
    op.drop_table('vouchers')
    op.drop_table('products')
    op.drop_table('loyalty_transactions')
    op.drop_table('carts')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
